### ISSUE TITLE
Clean junk out of HOT2000.options file(s)

### ISSUE THREAD

**Issue by fergusoa** [NRCan-IETS-CE-O-HBC/HTAP#10]
- Get rid of old ESP-r/dakota info 
- Eliminate tags that do nothing 
- Remove redundant definitions ( and possibly set up aliases )

**Comment by julia-purdy** [comment]
Removed most of the esp-r code from the HOT2000.options file. 
checked in:
https://github.com/NRCan-IETS-CE-O-HBC/HTAP/commit/0819556cb769a392c6efdb13e4bb3d7f6bbf44ee

**Comment by fergusoa** [comment]
legacy .options file now depriciated; htap-options.json file much cleaner.
