### ISSUE TITLE
Add additional reporting parameters required for NBC 

### ISSUE THREAD

**Issue by fergusoa** [NRCan-IETS-CE-O-HBC/HTAP#16]
From Adam Wills 

*Not yet supported (add)*
• Annual heat loss by envelope component 
• Annual DHW heating load [GJ] _-- heating load (or demand) on DHW system (before eff applied_)

 *Confirm already supported by HTAP*
- [x] Annual space heating fuel consumption _(Not available by fuel type -- see comment)_
- [x] Annual DHW fuel consumption _(Not available by fuel type -- see comment)_
- [x] Site electrical consumption
- [x] Site natural gas consumption
- [x] Site oil consumption
- [x] Space heating load _(Not provided in .h2k XML file - see comment)_
- [x] TEDI _(Needs to be improved - see comment)_

Add all new outputs to the screen dump and the output file (SubstitutePL-output.txt).  Add a new command line switch (something like `-e1`,`--extended-output1`) so we don't screw up existing tableau workbooks with these new outputs.

**Comment by jblake59** [comment]
@fergusoa : Could you expand on "Space heating load (through the TEDI???)"?

**Comment by jblake59** [comment]
Annual heat loss by envelope component. Total of all zones found here:
<AllResults>
   <Results houseCode="SOC" or output type specified in choices...>
      <Annual>
         <Load ...>
            <HeatLoss total=..., ceiling=..., etc.

So, new output variables will be added with names: *EnvHLTotal, EnvHLCeiling, EnvHLMainWalls, EnvHLWindows, EnvHLDoors, EnvHLExpFloors, EnvHLCrawlspace, EnvHLSlab, EnvHLBasementBGWall, EnvHLBasementAGWall, EnvHLBasementFlrHdrs, EnvHLPonyWall, EnvHLFlrsAbvBasement, EnvHLAirLkVent*.

**Comment by jblake59** [comment]
Annual space heating consumption and Annual DHW consumption are not provided in HTAP outputs by fuel type and have been added under the command line option "-e1" (i.e., extended output).

**Comment by jblake59** [comment]
The space heating load is assumed to be AuxEnergyReq-HeatingGJ that is currently provided in HTAP. This is the heating load that the heating system must provide to the spaces. It does not include for the efficiency of the space heating system energy conversion efficiency.

**Comment by jblake59** [comment]
The TEDI value is currently calculated for HTAP as:
>`$gAuxEnergyHeatingGJ * 277.78 / $FloorArea`

However, the `$FloorArea` value above relies on the sum of the above and below grade heated floor areas optionally entered by the file creator in the HOT2000 GUI House Specifications section. My review of a handful of H2K files reveals that this is seldom done.

To resolve this I will create a subroutine that estimates the total heated floor area based on either these house specification inputs, if they are reasonable, or a calculation using the outputs in the <Other><GrossArea> output section.

**Comment by jblake59** [comment]
Found a bug in the output section for <Annual><Consumption><Electrical> section. The total electrical energy attribute is always 0 GJ (v11.3b90)! I've reported this to OEE and worked around it by calculating the total electrical energy as the sum of it's components.
