### ISSUE TITLE
Review 9.36 use case with Adam, NRC

### ISSUE THREAD

**Issue by fergusoa** [NRCan-IETS-CE-O-HBC/HTAP#22]

**Comment by A-Wills** [comment]
When I run htap-prm.rb with DemoAW936Ruleset.run in HTAP\applications\NBC936-AW-ruleset I occasionally see the error "Could not find the whole-house ventilator list for ..." for different archetypes. I've tracked it down to the subroutine setVentilationRate in nbc_comply.pm
