### ISSUE TITLE
Allow for 9.36 rule sets in current htap-prm runs

### ISSUE THREAD

**Issue by jblake59** [NRCan-IETS-CE-O-HBC/HTAP#26]
Use a variation of Julia's PERL script code to allow for the generation of an appropriate archetype that can be used to run upgrades as specified in a ".run" file. The "RunScope" section of this file describes everything that's required to generate an archetype file for further analysis.

**Comment by jblake59** [comment]
*Approach 1* (from discussions Feb 19/18):
- Modify the .run file as required, including all rule set names required (i.e., 9.36 rule sets with %, 10 & 15% better)
- If the rule set name is one of AW's, proceed with htap-prm.rb code as-is, otherwise call a new Ruby script (either from within htap-prm.rb or external) that generates a modified archetype file that is compliant with the rule set specified. The new script will read the existing archetype file and determine the type of foundation, presence of HRV and any other aspect of the file it needs in order to set the 9.36 parameters and generate a new .h2k file with the original archetype name concatenated with the rule set name.

**Comment by jblake59** [comment]
*Approach 2* (from Julia's email Feb 19/18):
- Modify the .run file as required, including all rule set names required (i.e., 9.36 rule sets with %, 10 & 15% better)
- Create a stand-alone script from Julia's PERL script that generates the choices for the rule set specified in the .run file
- Call this new script from within substitute-h2k.rb so that choices are merged (i.e., rule set choices with .run choices). This would ensure that choices that do not comply with ruleset are not allowed.
- The new script will interrogate the existing model file (.h2k) to determine how to apply all of the rule set requirements.

**Comment by fergusoa** [comment]
I feel that approach #2 makes more sense because substitute-h2k.rb has access to the .h2k file contents and could potentially determine what kind of foundation / ventilation  requirements that would be needed for code rule sets.

**Comment by jblake59** [comment]
After a discussion with Alex, we have agreed that approach 2 (Julia's suggestion) will work best.

Note that if the .run file does not include an "NA" in every upgrade option list, then there won't be a reference output case generated.

**Comment by fergusoa** [comment]
Relocated this issue into -> HTAP v19: 9.36 Ruleset baked in!
