### ISSUE TITLE
Substitute-h2k.rb: Add support for different types of ceilings

### ISSUE THREAD

**Issue by fergusoa** [NRCan-IETS-CE-O-HBC/HTAP#3]
Provide support for changing the insulation in **ceilings of a specific construction type** rather than changing **all** ceilings to one insulation level. There are five (5) ceiling construction types in HOT2000: 

**Attic/gable, Attic/hip, Cathedral, Flat and Scissor**.  

Attic/gable and Attic/hip should be grouped together as they will have similar insulation levels.

**Comment by jblake59** [comment]
Proposal 1: I believe this can be achieved with the addition of new options that only find ceiling entries of a specific construction type as follows:
- Opt-Ceilings: The current option will remain as-is (change ALL ceilings)
- Opt-AtticCeilings: Change only ceilings of this construction type
- Opt-CathedralCeilings: Change only ceilings of this construction type
- Opt-FlatCeilings: Change only ceilings of this construction type
- Opt-ScissorCeilings: Change only ceilings of this construction type

**Comment by julia-purdy** [comment]
While i understand that scissors are their own ceiling "type", I think they can be lumped into cathedrals.

**Comment by jblake59** [comment]
@julia-purdy : Will do.  So grouping will be as follows:
- Opt-Ceilings: The current option will remain as-is (change ALL ceilings regardless of construction type). Note that this should **NOT** be used in conjunction with the new ones below!
- Opt-AtticCeilings: Change only ceilings of construction type **Attic/gable and Attic/hip**
- Opt-CathScissCeilings: Change only ceilings of construction type **Cathedral and Scissor**
- Opt-FlatCeilings: Change only ceilings of construction type **Flat**

**Comment by jblake59** [comment]
Note that the code library has two categories for ceiling codes: 
- Ceiling Codes (includes Attic/gable, Attic/hip, Scissor)
- Flat or Cathedral Ceiling Codes

They are split this way due to restrictions in some of the code layers.
