### ISSUE TITLE
getHeatedFloorArea in substitute-h2k.rb does not correctly calculate the heated floor area

### ISSUE THREAD

**Issue by fergusoa** [NRCan-IETS-CE-O-HBC/HTAP#33]
Bug reported by Adam W. on Gen-Dev: 

The method `getHeatedFloorArea` in substitute-h2k.rb does not correctly calculate the heated floor area of archetypes:

`numStoreysInput = elements["HouseFile/House/Specifications/Storeys"].attributes["code"].to_f`

- For a one storey dwelling this code is equal to 1
- For a two storey however, this code is equal to  3

For NRCan archetype 7 (two storey slab-on-grade), for example, the calculated floor area is 399 m2 and reported is 194 m2

**Comment by jblake59** [comment]
Silly mistake! The number of storeys input is a code that maps as follows:

   when 1
      numStoreysInput = 1
   when 2
      numStoreysInput = 1.5  # 1.5 storeys
   when 3
      numStoreysInput = 2
   when 4
      numStoreysInput = 2.5  # 2.5 storeys
   when 5
      numStoreysInput = 3
   when 6..7
      numStoreysInput = 2    # Split level or Spli entry/raised basement
