### ISSUE TITLE
substitute-h2k.rb: Add support for skylights, windows in doors

### ISSUE THREAD

**Issue by fergusoa** [NRCan-IETS-CE-O-HBC/HTAP#5]
Add the following window elements into HTAP:
- Windows in ceilings (i.e., skylights). Determine if also need to use the "Skylight" window type.
- Windows in doors
- The only other window element allowed in H2K is windows in closed crawlspaces and it may make sense to also add this

**Comment by jblake59** [comment]
I spent some time looking into Adam’s code and testing it out on various files. It works fine on files that have windows that use the 6 digit window codes (directly or through library favourites) but does not work for user defined window codes. As such, the method will not be added to HTAP at this time.

**Comment by jblake59** [comment]
Not quite done! Need to modify Hot2000.options and Hot2000.choices to include window types that are representative of those used in Skylights and doors. Note that there is a "Skylight" window type in the window code selector that probably should be used for skylights (I have the Enermodal docs on this).

@fergusoa : Are these the best files to modify or are there others?
