### ISSUE TITLE
substitute-h2k.rb: Verify treatment of vented & unvented crawl spaces

### ISSUE THREAD

**Issue by fergusoa** [NRCan-IETS-CE-O-HBC/HTAP#6]

**Comment by julia-purdy** [comment]
NRCan-arch2_1900sqft_1storey_crawlSpace.h2k: closed crawlspace. 
BASESIMP:  SCB_21

**Comment by julia-purdy** [comment]
[CrawlSpaceModel.docx](https://github.com/NRCan-IETS-CE-O-HBC/HTAP/files/1708290/CrawlSpaceModel.docx)
![crawl space testing](https://user-images.githubusercontent.com/7206972/35991294-c3efb760-0cd4-11e8-88fd-aa9f3065f9ab.png)

the crawlspace archetype was modified to represent:

1. closed crawlspace
2. vented crawlspace
3. open crawlspace

these archetypes were modified by HTAP-prm for several slab/wall configurations.

this analysis indicates that the thermal modelling is being modelled correctly

**Comment by fergusoa** [comment]
OK to close this issue?

**Comment by julia-purdy** [comment]
yes

Housing & Buildings R&D | CanmetENERGY-Ottawa
Natural Resources Canada | Government of Canada
julia.purdy@canada.ca<mailto:julia.purdy@canada.ca> | 647-404-7860

R&D – Bâtiments residentiels et commercieaux | CanmetÉNERGIE-Ottawa
Ressources naturelles Canada | Gouvernement du Canada
julia.purdy@canada.ca<mailto:julia.purdy@canada.ca> | 647-404-7860
